app/models.py
from app import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date = db.Column(db.String(100), nullable=False)
    content_html = db.Column(db.Text)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    date = StringField('Date', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    image_file = FileField('Cover Image', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Post')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'banana'
    #app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///../instance/site.db'
    db.init_app(app)

    from .routes import views
    app.register_blueprint(views, url_prefix='/')

    with app.app_context():
        #db.drop_all()
        print("db created!")
        db.create_all()

    return app

app/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, request, jsonify, send_from_directory, session
from .models import Post, db
from .forms import PostForm
from werkzeug.utils import secure_filename
import os

views = Blueprint('views', __name__)

@views.route('/static/images/<path:filename>')
def get_image(filename):
    #return send_from_directory(os.path.join(os.getcwd(), 'static/app/static/images'), filename)
    return send_from_directory(os.path.join(os.getcwd(), 'app/static/images'), filename)

@views.route('/')
def home():
    posts = Post.query.all()
    posts.reverse()
    return render_template('index.html', posts=posts)

@views.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@views.route('/about')
def about():
    return render_template('about.html')

@views.route('/admin_login', methods=['GET', 'POST'])
def admin_login():
    if request.method == 'POST':
        code = request.form['code']
        print(code)
        if code == '1234':
            session['admin_logged_in'] = True
            return redirect(url_for('views.admin_dashboard'))
        else:
            flash('Incorrect code. Please try again.', 'danger')
            print("WRONG")
            return redirect(url_for('views.admin_login'))
    return render_template('admin_login.html')

@views.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('views.home'))

@views.route('/admin_dashboard')
def admin_dashboard():
    if not session.get('admin_logged_in'):
        flash('Please log in as admin first.', 'danger')
        return redirect(url_for('views.admin_login'))
    
    return render_template('admin_dashboard.html')

@views.route('/delete_post')
def delete_post():
    if not session.get('admin_logged_in'):
        flash('Please log in as admin first.', 'danger')
        return redirect(url_for('views.admin_login'))
    
    posts = Post.query.all()
    posts.reverse()
    return render_template('delete_post.html', posts=posts)

@views.route('handle_delete_post/<int:post_id>', methods=['POST'])
def handle_delete_post(post_id):
    if not session.get('admin_logged_in'):
        flash('Please log in as admin first.', 'danger')
        return redirect(url_for('views.admin_login'))
    
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash(f'Post "{post.title}" deleted successfully!', 'success')
    return redirect(url_for('views.home'))

@views.route('/new_post', methods=['GET', 'POST'])
def new_post():
    if not session.get('admin_logged_in'):
        flash('Please log in as admin first.', 'danger')
        return redirect(url_for('views.admin_login'))
    
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        date = form.date.data
        content_html = request.form['content']
        content_html = content_html.replace('src="static/images/', 'src="/static/images/')
        image_file = form.image_file.data
        
        if image_file:
            filename = secure_filename(image_file.filename)
            #file_path = os.path.join(os.getcwd(), 'static/app/static/images', filename)
            file_path = os.path.join(os.getcwd(), 'app/static/images', filename)
            image_file.save(file_path)
        else:
            filename = 'default.jpg' #default image if none uploaded
        
        post = Post(title=title, date=date, content_html=content_html, image_file=filename)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created.', 'success')
        return redirect(url_for('views.home'))
    return render_template('new_post.html', title='New Post', form=form)

@views.route('/upload_image', methods=['POST'])
def upload_image():
    if 'image' not in request.files:
        return jsonify({'error': 'No image file provided'}), 400
    file = request.files['image']
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 400

    if file:
        filename = secure_filename(file.filename)
        #WHEN DEPLOYED USE THIS INSTEAD !!!
        #filepath = os.path.join('/home/nathanaelaou/mysite/app/static/images', filename)
        filepath = os.path.join(os.getcwd(), 'app/static/images', filename)
        file.save(filepath)
        # Return the URL of the uploaded image
        print(url_for('static', filename='images/' + filename, _external=False))
        return jsonify({'location': url_for('static', filename='images/' + filename)}), 201
    return jsonify({'error': 'Failed to upload image'}), 500

app/templates/about.html
{% extends "base.html" %}
{% block content %}
<div class="row about-row">
    <div class="col-md-6 d-flex align-items-center justify-content-center">
        <div class="about-img-wrapper">
            <img src="{{ url_for('static', filename='images/aboutme.png') }}" class="img-fluid about-img" alt="About Image">
        </div>
    </div>
    <div class="col-md-6 d-flex align-items-center">
        <div>
            <div class="post-title text-center">hi i'm nathanael</div>

            <p>i code. i erode. i explode.</p>
        </div>
    </div>
</div>
{% endblock %}

app/templates/admin_dashboard.html
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Admin Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% endwith %}
</head>
<body class="dashboard-bg">
    <div class="dashboard text-center">
        <div class="dashboard-container">
            <a href="{{ url_for('views.new_post') }}">Create New Post</a>
        </div>
        <div class="dashboard-container">
            <a href="{{ url_for('views.delete_post') }}">Delete a Post</a>
        </div>
        <div class="dashboard-container">
            <a href="{{ url_for('views.logout') }}">Back</a>
        </div>
    </div>
</body>
</html>

app/templates/admin_login.html
{% extends "base.html" %}
{% block content %}
<body>
    <div class="container login-container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form action="{{ url_for('views.admin_login') }}" method="post">
                    <div class="form-group">
                        <label for="code">Enter 4-digit code to login as admin:</label>
                        <input type="password" class="form-control" id="code" name="code" maxlength="4" required>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Login</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />

        <!-- FONTS -->
        <link href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&display=swap" rel="stylesheet">


        <title>{% block title %}My Website{% endblock %}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg custom-navbar">
            <div class="col-1 text-left">
                <a class="navbar-blog" href="{{ url_for('views.home') }}">Blog</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.home') }}"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-muted" href="{{ url_for('views.about') }}">About Me</a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Content -->
        <div class="content-wrapper">
            {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            <div class="custom-container">
                {% block content %}
                {% endblock %}
            </div>
        </div>

        <!-- Footer -->
        <footer class="footer">
            <div class="container-fluid">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-3 text-left">
                            <span class="text-muted">&copy; 2024 Nathanael Aou</span>
                        </div>
                        <div class="col-lg-9 text-right">
                            <a class="nav-link text-muted" href="{{ url_for('views.admin_login') }}">Admin Login</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poTq6e1p6K7V3y0IYd6MOeI6YAm0E3gkMc1Rg8A2BjpZbPBHEG7" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-pzjw8f+ua7Kw1TIq1F8+0xIepnQns5JzUop43eUAAopF7b2Q6JxawIj9sfsPb9C2" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-0Fzq6t7MxWqQ2ULSogT6IsF0u7bB+F0Qpqt1F3Spx8nxFJwwc5q1p7XDzjP/Cf1N" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/delete_post.html
{% extends "base.html" %}
{% block title %}Delete Post{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 mt-5">
    {% for post in posts %}
    <div class="col-md-3 mb-5 custom-column d-flex flex-column align-items-center">
        {% if post.image_file %}
            <div class="delete-post-img-wrapper">
                <img src="{{ url_for('static', filename='images/' ~ post.image_file) }}" class="delete-post-img" alt="{{ post.title }}">
            </div>
        {% else %}
            <p>No image available</p>
        {% endif %}
        <h3 class="text-center">{{ post.title }}</h3>

        <form id="deleteForm{{ post.id }}" method="post" action="{{ url_for('views.handle_delete_post', post_id=post.id) }}">
            <!-- Delete button with onclick event -->
            <button type="button" class="btn btn-danger" onclick="confirmDelete('{{ post.id }}')">Delete</button>
        </form>

    </div>
    {% endfor %}
</div>

<script>
// JavaScript function to display confirmation dialog
function confirmDelete(postId) {
    if (confirm("Are you sure you want to delete this post?")) {
        document.getElementById('deleteForm' + postId).submit(); // Submit the form
    }
}
</script>

{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<h1 class="my-4 text-center custom-heading">Nathanael's Blog</h1>
<div class="row row-cols-1 row-cols-md-3">
    {% for post in posts %}
    <div class="col-md-4 mb-5 custom-column">
        <div class="card custom-card">
            <a href="{{ url_for('views.post', post_id=post.id) }}" draggable="false">
                <div class="custom-card-img-wrapper">
                    <img src="{{ url_for('static', filename='images/' ~ post.image_file) }}" class="card-img-top custom-card-img" draggable="false" alt="{{ post.title }}">
                </div>
                <div class="card-body">
                    <h3 class="card-date">{{ post.date }}</h3>
                    <h2 class="card-title">{{ post.title }}</h2>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/new_post.html
{% extends "base.html" %}
{% block title %}New Post{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mt-4">Create a New Post</h1>
    <form method="POST" action="{{ url_for('views.new_post') }}" enctype="multipart/form-data" nonvalidate>
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label(class="form-label") }}
            {{ form.title(class="form-control", required=True) }}
        </div>
        <div class="form-group">
            {{ form.date.label(class="form-label") }}
            {{ form.date(class="form-control", required=True) }}
        </div>
        <div class="form-group">
            {{ form.content.label(class="form-label") }}
            {{ form.content(class="form-control", id='content', required=False) }}
        </div>
        <div class="form-group">
            {{ form.image_file.label(class="form-label") }}
            {{ form.image_file(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
<script src="https://cdn.tiny.cloud/1/j97a1p3p7gcu7mjadbxub8ftzdqa2ob8sv0axfhpwc90xvq8/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        tinymce.init({
            selector: '#content',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage advtemplate ai mentions tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss markdown',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
            automatic_uploads: true,
            images_upload_url: '/upload_image',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
            ],
            ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),

            images_upload_handler: function (blobInfo, progress) {
                return new Promise(function (resolve, reject) {
                    var xhr, formData;
                    xhr = new XMLHttpRequest();
                    xhr.withCredentials = false;
                    xhr.open('POST', '/upload_image');

                    // Track upload progress
                    xhr.upload.onprogress = function(e) {
                        if (e.lengthComputable) {
                            var percentComplete = (e.loaded / e.total) * 100;
                            progress(percentComplete);
                        }
                    };

                    xhr.onload = function() {
                        if (xhr.status === 201) {
                            var json = JSON.parse(xhr.responseText);
                            if (json && typeof json.location === 'string') {
                                resolve(json.location); // Resolve with the image URL
                            } else {
                                reject('Invalid JSON: ' + xhr.responseText); // Reject with an error message
                            }
                        } else {
                            reject('HTTP Error: ' + xhr.status); // Reject with an HTTP error
                        }
                    };

                    xhr.onerror = function() {
                        reject('Network Error'); // Reject with a network error
                    };

                    formData = new FormData();
                    formData.append('image', blobInfo.blob(), blobInfo.filename());
                    xhr.send(formData);
                });
            }
        });
    });
</script>
{% endblock %}

app/templates/post.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="post-title text-center">
    {{ post.title }}
</div>
<div class="post-date text-center">
    {{ post.date }}
</div>
<div class = 'post-content'>
    {{ post.content_html | safe }}
</div>
{% endblock %}